silant_app/base/urls.py
from django.urls import path
from .views import InfoListView, TOListView, ReclamationListView, MachineDetailView, TOCreateView, ReclamationCreateView, \
    TOUpdateView, ReclamationUpdateView, TODeleteView, ReclamationDeleteView, SpravochnikDetailView

urlpatterns = [
    path('', InfoListView.as_view(), name='base'),
    path('<int:pk>/', MachineDetailView.as_view(), name='machine'),
    path('<int:pk>/add/to', TOCreateView.as_view(), name='to_create'),
    path('update/to/<int:pk>', TOUpdateView.as_view(), name='to_update'),
    path('delete/to/<int:pk>', TODeleteView.as_view(), name='to_delete'),
    path('<int:pk>/add/reclamation', ReclamationCreateView.as_view(), name='reclam_create'),
    path('update/reclamation/<int:pk>', ReclamationUpdateView.as_view(), name='reclam_update'),
    path('delete/reclamation/<int:pk>', ReclamationDeleteView.as_view(), name='reclam_delete'),
    path('maintenance/', TOListView.as_view(), name='main'),
    path('reclamations/', ReclamationListView.as_view(), name='reclamation'),
    path('spravochnik/<int:pk>', SpravochnikDetailView.as_view(), name='sprav'),
]

silant_app/silant_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

silant_app/base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.functions.datetime import ExtractDay


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile',)
    name = models.CharField(max_length=126,  verbose_name='Описание')

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.user

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


class Machine(models.Model):
    number = models.CharField(max_length=50, unique=True, verbose_name='Зав. № машины')
    tech_model = models.ForeignKey('Spravochnik', on_delete=models.CASCADE,
                                   related_name='techs',
                                   limit_choices_to={'type_name': 'TC'},
                                   verbose_name='Модель техники')
    eng_model = models.ForeignKey('Spravochnik', on_delete=models.CASCADE,
                                  related_name='engines',
                                  limit_choices_to={'type_name': 'EN'},
                                  verbose_name='Модель двигателя')
    eng_num = models.CharField(max_length=50, unique=True, verbose_name='Зав. № двигателя')
    tran_model = models.ForeignKey('Spravochnik', on_delete=models.CASCADE,
                                   related_name='trans',
                                   limit_choices_to={'type_name': 'TR'},
                                   verbose_name='Модель трансмиссии')
    tran_num = models.CharField(max_length=50, unique=True, verbose_name='Зав. № трансмиссии')
    drive_axle = models.ForeignKey('Spravochnik', on_delete=models.CASCADE,
                                   related_name='drives',
                                   limit_choices_to={'type_name': 'DA'},
                                   verbose_name='Модель ведущего моста')
    drive_num = models.CharField(max_length=50, unique=True, verbose_name='Зав. № ведущего моста')
    steer_axle = models.ForeignKey('Spravochnik', on_delete=models.CASCADE,
                                   related_name='steers',
                                   limit_choices_to={'type_name': 'SA'},
                                   verbose_name='Модель управляемого моста')
    steer_num = models.CharField(max_length=50, unique=True, verbose_name='Зав. № управляемого моста')
    dogovor = models.CharField(max_length=126, verbose_name='Договор поставки №, дата')
    shipping_date = models.DateField(verbose_name='Дата отгрузки с завода')
    consumer = models.CharField(max_length=126, verbose_name='Грузополучатель (конечный потребитель)')
    address = models.CharField(max_length=126, verbose_name='Адрес поставки (эксплуатации)')
    package = models.TextField(default="Стандарт", verbose_name='Комплектация (доп. опции)')
    client = models.ForeignKey(UserProfile, on_delete=models.CASCADE,
                               related_name='clients',
                               limit_choices_to={'user__groups__name': 'Клиент'},
                               verbose_name='Клиент')
    service = models.ForeignKey('Spravochnik', on_delete=models.CASCADE,
                                related_name='service_machines',
                                limit_choices_to={'type_name': 'SR'},
                                verbose_name='Сервисная компания')

    class Meta:
        verbose_name = 'Машина'
        verbose_name_plural = 'Машины'

    def __str__(self):
        return 'Номер машины: {}'.format(self.number)


class TO(models.Model):
    machine = models.ForeignKey('Machine', on_delete=models.CASCADE,
                                related_name='machine_to',
                                verbose_name='Машина')
    type = models.ForeignKey('Spravochnik', on_delete=models.CASCADE,
                             related_name='types',
                             limit_choices_to={'type_name': 'TO'},
                             verbose_name='Вид ТО')
    to_date = models.DateField(verbose_name='Дата проведения ТО')
    operating = models.IntegerField(default=0, verbose_name='Наработка, м/час')
    order_num = models.CharField(max_length=50, verbose_name='№ заказ-наряда')
    order_date = models.DateField(verbose_name='Дата заказ-наряда')
    service = models.ForeignKey('Spravochnik', on_delete=models.CASCADE,
                                related_name='service_to',
                                limit_choices_to={'type_name': 'SR'},
                                verbose_name='Сервисная компания')

    class Meta:
        verbose_name = 'Техническое обслуживание'
        verbose_name_plural = 'Технические обслуживания'

    def __str__(self):
        return 'Заказ-наряд: {}'.format(self.order_num)


class Reclamation(models.Model):
    machine = models.ForeignKey('Machine', on_delete=models.CASCADE,
                                related_name='machine_reclams',
                                verbose_name='Машина')
    fail_date = models.DateField(verbose_name='Дата отказа')
    operating = models.IntegerField(default=0, verbose_name='Наработка, м/час')
    fail_node = models.ForeignKey('Spravochnik', on_delete=models.CASCADE,
                                  related_name='fails',
                                  limit_choices_to={'type_name': 'FT'},
                                  verbose_name='Узел отказа')
    fail_descrip = models.CharField(max_length=126, verbose_name='Описание отказа')
    recovery = models.ForeignKey('Spravochnik', on_delete=models.CASCADE,
                                 related_name='recovers',
                                 limit_choices_to={'type_name': 'RE'},
                                 verbose_name='Способ восстановления')
    parts = models.CharField(max_length=126, verbose_name='Используемые запасные части')
    recovery_date = models.DateField(verbose_name='Дата восстановления')
    idleness = models.IntegerField(default=0, verbose_name='Время простоя техники')
    service = models.ForeignKey('Spravochnik', on_delete=models.CASCADE,
                                related_name='service_reclams',
                                limit_choices_to={'type_name': 'SR'},
                                verbose_name='Cервисная компания')

    def __str__(self):
        return '{} с отказом: {}'.format(self.machine, self.fail_descrip)

    """Функция, вызываемая в сигнале post_save: расчет количества дней"""
    def duration(self):
        days = (self.recovery_date - self.fail_date).days
        return days

    class Meta:
        verbose_name = 'Рекламация'
        verbose_name_plural = 'Рекламации'


class Spravochnik(models.Model):
    TECHNIQUE = 'TC'
    ENGINE = 'EN'
    TRANSMISSION = 'TR'
    DRIVE_AXLE = 'DA'
    STEERING_AXLE = 'SA'
    TO_TYPE = 'TO'
    FAILURE = 'FT'
    RECOVERY = 'RE'
    SERVICE = 'SR'
    HANDBOOK_CHOICES = [
        (TECHNIQUE, 'Модель техники'),
        (ENGINE, 'Модель двигателя'),
        (TRANSMISSION, 'Модель трансмиссии'),
        (DRIVE_AXLE, 'Модель ведущего моста'),
        (STEERING_AXLE, 'Модель управляемого моста'),
        (TO_TYPE, 'Вид TO'),
        (FAILURE, 'Характер отказа'),
        (RECOVERY, 'Способ восстановления'),
        (SERVICE, 'Сервисная компания'),
    ]
    type_name = models.CharField(
        max_length=2,
        choices=HANDBOOK_CHOICES,
        default='Не указано',
        verbose_name='Название справочника'
    )
    name = models.CharField(max_length=256, db_index=True, verbose_name='Название')
    description = models.CharField(max_length=2000, default='Отсутствует', verbose_name='Описание')

    class Meta:
        verbose_name = 'Справочник'
        verbose_name_plural = 'Справочники'

    def __str__(self):
        return self.name

# Create your models here.

silant_app/templates/default.html
{% extends 'layout.html' %}

{% block content %}

{% if request.user.is_authenticated %}
    {% include "users_info.html"  %}
{% else %}
<div class="container">
    <div class="head-container">
        <h3>Проверьте комплектацию и технические характеристики техники Силант</h3>

        <form action="" method="get">
            {{ filterset.form.non_field_errors }}
            {{ filterset.form.number.errors }}

            <input
                id="{{ filterset.form.number.id }}"
                placeholder="Зав. № машины"
                name="{{ filterset.form.number.name }}"
            >
            <input type="submit" class="mt-3 btn-primary" value="Найти" />
        </form>
        <hr>
    </div>
    <div class="info-container">
        {%if messages %}
            <div class="alert alert-success">
                {% for m in messages %}
                    {{m|safe}}
                {% endfor %}
            </div>
        {% endif %}
        {% if is_set %}
            {% if machines.qs %}
                <p> Информация о комплектации и технических характеристиках Вашей техники</p>
                <div class="scroll-table">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>Модель техники</th>
                            <th>Модель двигателя</th>
                            <th>Зав. № двигателя</th>
                            <th>Модель трансмиссии</th>
                            <th>Зав. № трансмиссии</th>
                            <th>Модель ведущего моста</th>
                            <th>Зав. № ведущего моста</th>
                            <th>Модель управляемого моста</th>
                            <th>Зав. № управляемого моста</th>
                        </tr>
                        </thead>
                        {% for machine in machines.qs %}
                        <tbody>
                        <tr>
                            <td>{{ machine.tech_model }}</td>
                            <td>{{ machine.eng_model }}</td>
                            <td>{{ machine.eng_num }}</td>
                            <td>{{ machine.tran_model }}</td>
                            <td>{{ machine.tran_num }}</td>
                            <td>{{ machine.drive_axle }}</td>
                            <td>{{ machine.drive_num }}</td>
                            <td>{{ machine.steer_axle }}</td>
                            <td>{{ machine.steer_num }}</td>
                        </tr>
                        </tbody>
                        {%endfor%}
                    </table>
                </div>
                <br>
            {% else %}
                <h2>По данному номеру машин нет!</h2>
            {% endif %}
        {% endif %}
    </div>


</div>


{% endif %}
{% endblock content %}

silant_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        {% load static %}
        <!-- Bootstrap CSS (jsDelivr CDN) -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css">
        <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
        <title>Силант</title>

    </head>
    <body>

    <div class="wrapper">
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark static-top">
           <div class="container">
               <a class="navbar-brand" href="/">
                   <img width="100" src="{% static 'images/logo.jpg' %}" >
               </a>
               <button class="navbar-toggler" type="button" data-toggle="collapse"
                       data-target="#navbarResponsive"
                       aria-controls="navbarResponsive" aria-expanded="false"
                       aria-label="Toggle navigation">
                   <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarResponsive">
                   <ul class="navbar-nav ml-auto">
                       <li class="nav-item">
                           <a class="nav-link m-2" href="/">Главная</a>
                       </li>
                       <li class="nav-item">
                           {% if request.user.is_authenticated %}
                              <a class="nav-link m-2" href="/accounts/logout/">Выйти</a>
                           {% else %}
                              <a class="nav-link m-2" href="/accounts/login/">Авторизация</a>
                           {% endif %}
                       </li>
                       <li class="nav-item">
                           <p class="nav-link m-2" >telegram: +7-8352-20-12-09</p>
                       </li>
                   </ul>
               </div>
               <div>
                   <p class="text-light m-2">Электронная сервисная книжка "Мой Силант"</p>
               </div>
           </div>
        </nav>

        <!-- Page content-->
        <div class="main-info container">
           <div class="row">
               <div class="col-lg-12 text-center">
                   {% block content %}
                   {% endblock content %}
               </div>
           </div>
        </div>
    </div>
        <!-- Footer -->
        <footer class="text-center text-white">
          <!-- Grid container -->
          <div class="container p-2">
            <!-- Section: Social media -->
            <section class="m-2">
                <p style="margin: 0;">
                Telegram: +7-8352-20-12-09
              </p>
            </section>
          </div>

          <div class="text-center p-2" style="background-color: rgba(0, 0, 0, 0.2);">
            Мой Силант 2023
          </div>

        </footer>

    </body>
</html>

silant_app/templates/machine.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="head-container">

        <h3>Машина: {{machine.number}}</h3>

        <div class="buttons">
            <button onclick="myFunction1()" class="btn btn-primary"> Общая информация </button>
            <button onclick="myFunction2()" class="btn btn-primary"> ТО </button>
            <button onclick="myFunction3()" class="btn btn-primary"> Рекламации </button>
        </div>
        <hr>
    </div>

    <div class="info-container">
        <p> Информация о комплектации и технических характеристиках Вашей техники</p>
        {%if messages %}
            <div class="alert alert-success">
                {% for m in messages %}
                    {{m|safe}}
                {% endfor %}
            </div>
        {% endif %}
        <div id="machineInfo" class="scroll-table">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Модель техники</th>
                    <th>Зав. № двигателя</th>
                    <th>Зав. № трансмиссии</th>
                    <th>Зав. № ведущего моста</th>
                    <th>Зав. № управляемого моста</th>
                    <th>Покупатель</th>
                    <th>Грузополучатель</th>
                    <th>Адрес поставки</th>
                    <th>Комплектация</th>
                    <th>Сервисная компания</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="selected">
                        <a class="ref text-dark" href="{% url 'sprav' machine.tech_model.id %}">{{ machine.tech_model }}</a>
                    </td>
                    <td class="selected">
                        <a class="ref text-dark" href="{% url 'sprav' machine.eng_model.id %}"> {{ machine.eng_num }}</a>
                    </td>
                    <td class="selected">
                        <a class="ref text-dark" href="{% url 'sprav' machine.tran_model.id %}">{{ machine.tran_num }}</a>
                    </td>
                    <td class="selected">
                        <a class="ref text-dark" href="{% url 'sprav' machine.drive_axle.id %}">{{ machine.drive_num }}</a>
                    </td>
                    <td class="selected">
                        <a class="ref text-dark" href="{% url 'sprav' machine.steer_axle.id %}">{{ machine.steer_num }}</a>
                    </td>
                    <td>{{ machine.client.name }}</td>
                    <td>{{ machine.consumer }}</td>
                    <td>{{ machine.address }}</td>
                    <td>{{ machine.package }}</td>
                    <td class="selected">
                        <a class="ref text-dark" href="{% url 'sprav' machine.service.id %}">{{ machine.service }}</a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>

        <div id="toInfo">
            {% include "machine_to.html"  %}
        </div>

        <div id="reclamsInfo">
            {% include "machine_reclams.html"  %}
        </div>
    </div>

</div>


{% endblock content %}

silant_app/templates/machine_reclams.html
{% block content %}
    {% if reclam_list %}
        <div class="scroll-table">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Дата отказа</th>
                    <th>Наработка, м/час</th>
                    <th>Узел отказа</th>
                    <th>Описание отказа</th>
                    <th>Способ восстановления</th>
                    <th>Используемые запасные части</th>
                    <th>Дата восстановления</th>
                    <th>Время простоя техники</th>
                    <th>Сервисная организация</th>
                    {% if not is_client%}<th class="btn-field"></th>{% endif %}
                </tr>
                </thead>
                    {% for reclam in reclam_list %}
                        <tbody>
                        <tr>
                            <td>{{ reclam.fail_date }}</td>
                            <td>{{ reclam.operating }}</td>
                            <td class="selected">
                                <a class="ref text-dark" href="{% url 'sprav' reclam.fail_node.id %}">{{ reclam.fail_node }}</a>
                            </td>
                            <td>{{ reclam.fail_descrip }}</td>
                            <td class="selected">
                                <a class="ref text-dark" href="{% url 'sprav' reclam.recovery.id %}">{{ reclam.recovery  }}</a>
                            </td>
                            <td>{{ reclam.parts }}</td>
                            <td>{{ reclam.recovery_date }}</td>
                            <td>{{ reclam.idleness }} дней</td>
                            <td class="selected">
                                <a class="ref text-dark" href="{% url 'sprav' reclam.service.id %}">{{ reclam.service }}</a>
                            </td>
                            {% if not is_client%}
                                <td>
                                    <button class="btn btn-secondary mb-2">
                                        <a class="ref" href="{% url 'reclam_update' reclam.id %}">Изменить</a>
                                    </button>
                                    <button class="btn btn-danger">
                                        <a class="ref text-light" href="{% url 'reclam_delete' reclam.id %}">Удалить</a>
                                    </button>
                                </td>
                            {% endif %}
                        </tr>
                        </tbody>
                    {%endfor%}
            </table>
        </div>

    {% else %}
        <h2>Данных по рекламациям не обнаружено</h2>
    {% endif %}
    {% if not is_client%}
        <button class="btn btn-secondary mt-3">
            <a class="ref" href="{% url 'reclam_create' machine.id %}">Добавить данные</a>
        </button>
    {% endif %}
{% endblock content %}

silant_app/templates/machine_to.html
{% block content %}
    {% if to_list %}
        <div class="scroll-table">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Вид ТО</th>
                    <th>Дата проведения ТО</th>
                    <th>Наработка, м/час</th>
                    <th>№ заказ-наряда</th>
                    <th>Дата заказ-наряда</th>
                    <th>Организация, проводившая ТО</th>
                    <th class="btn-field"></th>
                </tr>
                </thead>
                <tbody>
                    {% for to in to_list %}
                        <tr>
                            <td class="selected">
                                <a class="ref text-dark" href="{% url 'sprav' to.type.id %}">{{ to.type }}</a>
                            </td>
                            <td>{{ to.to_date }}</td>
                            <td>{{ to.operating }}</td>
                            <td>{{ to.order_num }}</td>
                            <td>{{ to.order_date }}</td>
                            <td class="selected">
                                <a class="ref text-dark" href="{% url 'sprav' to.service.id %}">{{ to.service }}</a>
                            </td>
                            <td>
                                <button class="btn btn-secondary mb-2">
                                    <a class="ref" href="{% url 'to_update' to.id %}">Изменить</a>
                                </button>
                                <button class="btn btn-danger">
                                    <a class="ref text-light" href="{% url 'to_delete' to.id %}">Удалить</a>
                                </button>
                            </td>
                        </tr>

                    {%endfor%}
                </tbody>
            </table>
        </div>

    {% else %}
        <h2>Данных по техническому обслуживанию не обнаружено</h2>
    {% endif %}

    <button class="btn btn-secondary mt-3">
        <a class="ref" href="{% url 'to_create' machine.id %}">Добавить данные</a>
    </button>
{% endblock content %}

silant_app/templates/rec_delete.html
{% extends 'layout.html' %}

{% block content %}

<div class="container">
    <div class="head-container">

        <br>
        <h3>Вы действительно хотите удалить данные?</h3>

        <hr>
    </div>
    <div class="info-container">
        <p> Информация о рекламации</p>
        <div class="scroll-table">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Зав. № машины</th>
                        <th>Дата отказа</th>
                        <th>Наработка, м/час</th>
                        <th>Узел отказа</th>
                        <th>Описание отказа</th>
                        <th>Способ восстановления</th>
                        <th>Используемые запасные части</th>
                        <th>Дата восстановления</th>
                        <th>Время простоя техники</th>
                        <th>Сервисная организация</th>
                    </tr>
                </thead>
                    <tbody>
                    <tr>
                        <td>{{ reclam.machine.number }}</td>
                        <td>{{ reclam.fail_date }}</td>
                        <td>{{ reclam.operating }}</td>
                        <td>{{ reclam.fail_node }}</td>
                        <td>{{ reclam.fail_descrip }}</td>
                        <td>{{ reclam.recovery  }}</td>
                        <td>{{ reclam.parts }}</td>
                        <td>{{ reclam.recovery_date }}</td>
                        <td>{{ reclam.idleness }} дней</td>
                        <td>{{ reclam.service }}</td>
                    </tr>
                    </tbody>
            </table>
        </div>
    </div>
</div>


<form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-success" value="подтвердить">
</form>

{% endblock content %}

silant_app/templates/reclam_create.html
{% extends 'layout.html' %}

{% load widget_tweaks %}

{% block content %}
<div class="container">
    <h2>Добавьте информацию о рекламациях вашей техники</h2>
    <h3>{{machine}}</h3>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Сохранить</button>
    </form>


</div>
{% endblock content %}

silant_app/templates/reclams.html
{% extends 'layout.html' %}

{% block content %}

<div class="container">
    <div class="head-container">
        <div class="userInfo">
            {% if is_client%}
                Клиент: {{ request.user.profile.name }}
            {% else %}
                {% if is_service %}
                    Сервисная компания: {{ request.user.profile.name }}
                {% else %}
                    Страница менеджера
                {% endif %}
            {% endif %}
        </div>
        <br>
        <h3>Проверьте комплектацию и технические характеристики техники Силант</h3>

        <div class="buttons">
            <button class="btn btn-primary"> <a class="ref text-white" href="/">Общая информация</a> </button>
            <button class="btn btn-primary"> <a class="ref text-white" href="{% url 'main' %}">ТО</a> </button>
            <button class="btn btn-primary"> <a class="ref text-white" href="{% url 'reclamation' %}">Рекламации</a> </button>
        </div>
        <hr>
    </div>
    <div class="info-container">
        <div class="fil-form">
            <form action="" method="get" >
                 <div class="filter-form">
                     {% for field in filterset.form %}
                         <div>
                             {{ field.label_tag }}
                             {{ field }}
                         </div>

                     {% endfor %}
                 </div>
                <input class="btn btn-secondary mb-4 mt-3" type="submit" value="Найти" />
            </form>
        </div>
        {% if is_exist %}
            <p> Информация о комплектации и технических характеристиках Вашей техники</p>
            <div class="scroll-table">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Зав. № машины</th>
                        <th>Дата отказа</th>
                        <th>Наработка, м/час</th>
                        <th>Узел отказа</th>
                        <th>Описание отказа</th>
                        <th>Способ восстановления</th>
                        <th>Используемые запасные части</th>
                        <th>Дата восстановления</th>
                        <th>Время простоя техники</th>
                        <th>Сервисная организация</th>
                    </tr>
                    </thead>
                    {% for reclam in filterset.qs %}
                        {% if reclam.machine in users_machines %}
                            <tbody>
                            <tr>
                                <td class="selected">
                                    <a class="ref text-dark" href="{% url 'machine' reclam.machine.id %}">{{ reclam.machine.number }}</a>
                                </td>
                                <td>{{ reclam.fail_date }}</td>
                                <td>{{ reclam.operating }}</td>
                                <td class="selected">
                                    <a class="ref text-dark" href="{% url 'sprav' reclam.fail_node.id %}">{{ reclam.fail_node }}</a>
                                </td>
                                <td>{{ reclam.fail_descrip }}</td>
                                <td class="selected">
                                    <a class="ref text-dark" href="{% url 'sprav' reclam.recovery.id %}">{{ reclam.recovery  }}</a>
                                </td>
                                <td>{{ reclam.parts }}</td>
                                <td>{{ reclam.recovery_date }}</td>
                                <td>{{ reclam.idleness }} дней</td>
                                <td class="selected">
                                    <a class="ref text-dark" href="{% url 'sprav' reclam.service.id %}">{{ reclam.service }}</a>
                                </td>
                            </tr>
                            </tbody>
                        {% endif %}
                    {%endfor%}
                </table>
            </div>
            <br>
        {% else %}
            <h2>Данных по рекламациям не обнаружено</h2>
        {% endif %}
    </div>


</div>


{% endblock content %}

silant_app/templates/sprav_detail.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="head-container">
        <h3>Справочник с информацией</h3>
        <hr>
    </div>

    <div class="info-container">
        <div >
            <table class="spravochnik table table-bordered">
                <thead>
                <tr>
                    <th>{{ type_name }}</th>
                    <th>Описание</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ sprav.name }}</td>
                    <td>{{ sprav.description }}</td>

                </tr>
                </tbody>
            </table>
        </div>

    </div>

</div>


{% endblock content %}